name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_TAG: 2023.08.09

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Dependencies
      - name: vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{runner.os}}-vcpkg-${{env.VCPKG_TAG}}

      - uses: actions/checkout@v3
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        with:
          repository: Microsoft/vcpkg
          ref: ${{env.VCPKG_TAG}}
          path: vcpkg

      - name: Build dependencies
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/vcpkg
        run: |
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install boost-algorithm:x64-windows boost-container:x64-windows boost-filesystem:x64-windows boost-heap:x64-windows box2d:x64-windows freetype:x64-windows pugixml:x64-windows sdl2:x64-windows stb:x64-windows zlib:x64-windows

      # Prises build
      - uses: actions/checkout@v3
        with:
          path: prises
          submodules: 'true'

      - name: Configure Prises
        run: cmake -S ${{github.workspace}}/prises/ -B ${{github.workspace}}/prises/build -DCMAKE_UNITY_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -T host=x64 -A x64

      - name: Build Prises
        run: cmake --build ${{github.workspace}}/prises/build --config ${{env.BUILD_TYPE}} --parallel

      - name: Create snapshot
        working-directory: ${{github.workspace}}/prises/build
        run: cpack --config CPackConfig.cmake -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v3
        with:
          name: prises-snapshot
          path: ${{github.workspace}}/prises/build/*.zip
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest

    steps:
      # Dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev libboost-dev libfreetype6-dev zlib1g-dev libpugixml-dev libbox2d-dev

      # Prises build
      - uses: actions/checkout@v3
        with:
          path: prises
          submodules: 'true'

      - name: Configure Prises
        run: cmake -S ${{github.workspace}}/prises/ -B ${{github.workspace}}/prises/build -DCMAKE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/gf/build/install

      - name: Build Prises
        run: cmake --build ${{github.workspace}}/prises/build --config ${{env.BUILD_TYPE}} --parallel

  build-macos:
    runs-on: macos-latest

    env:
      VCPKG_ROOT: ${{github.workspace}}/vcpkg

    steps:
      # Dependencies
      - name: vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{runner.os}}-vcpkg-${{env.VCPKG_TAG}}

      - uses: actions/checkout@v3
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        with:
          repository: Microsoft/vcpkg
          ref: ${{env.VCPKG_TAG}}
          path: vcpkg

      - name: Build dependencies
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/vcpkg
        run: |
          ./bootstrap-vcpkg.sh
          ./vcpkg install boost-algorithm:x64-osx boost-container:x64-osx boost-filesystem:x64-osx boost-heap:x64-osx box2d:x64-osx freetype:x64-osx pugixml:x64-osx sdl2:x64-osx stb:x64-osx zlib:x64-osx

      # Prises build
      - uses: actions/checkout@v3
        with:
          path: prises
          submodules: 'true'

      - name: Configure Prises
        run: cmake -S ${{github.workspace}}/prises/ -B ${{github.workspace}}/prises/build -DCMAKE_UNITY_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Prises
        run: cmake --build ${{github.workspace}}/prises/build --config ${{env.BUILD_TYPE}} --parallel
