name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{github.workspace}}/vcpkg

    steps:
      # Install gf via vcpkg
      - name: vcpkg cache
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: vcpkg
          key: ${{ runner.os }}-vcpkg-2022.09.27

      - uses: actions/checkout@v3
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        with:
          repository: Microsoft/vcpkg
          ref: 2022.09.27
          path: vcpkg

      - name: Build gf
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}/vcpkg
        run: |
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install gamedev-framework:x64-windows box2d:x64-windows

      # Prises build
      - uses: actions/checkout@v3
        with:
          path: prises
          submodules: 'true'

      - name: Configure Prises
        run: cmake -S ${{github.workspace}}/prises/ -B ${{github.workspace}}/prises/build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -T host=x64 -A x64

      - name: Build Prises
        run: cmake --build ${{github.workspace}}/prises/build --config ${{env.BUILD_TYPE}} --parallel

      - name: Create snapshot
        working-directory: ${{github.workspace}}/prises/build
        run: cpack --config CPackConfig.cmake -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v3
        with:
          name: prises-snapshot
          path: ${{github.workspace}}/prises/build/*.zip
          if-no-files-found: error
